# Generated by Django 5.1.4 on 2025-01-30 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company_official_mail',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='trial_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 16, 26, 55, 241495, tzinfo=datetime.timezone.utc)),
        ),
    ]
