# Generated by Django 5.0.2 on 2024-12-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='num_certificates_uploaded',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
