# Generated by Django 5.1.4 on 2025-01-13 08:00

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization_num_certificates_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 8, 0, 20, 301787, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
