# Generated by Django 5.1.4 on 2025-01-30 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization_company_official_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='trial_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 16, 27, 48, 889559, tzinfo=datetime.timezone.utc)),
        ),
    ]
