# Generated by Django 5.1.4 on 2025-01-30 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_organization_trial_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='trial_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 16, 28, 33, 76340, tzinfo=datetime.timezone.utc)),
        ),
    ]
