# Generated by Django 5.1.4 on 2025-01-15 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_organization_trial_end_date_backgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='trial_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 14, 17, 3, 14, 798518, tzinfo=datetime.timezone.utc)),
        ),
    ]
