# Generated by Django 5.1.4 on 2025-02-01 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_organization_trial_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='trial_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 3, 14, 22, 8, 249935, tzinfo=datetime.timezone.utc)),
        ),
    ]
