# Generated by Django 5.1.4 on 2025-01-16 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_backgroundimage_is_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='trial_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 9, 29, 52, 270479, tzinfo=datetime.timezone.utc)),
        ),
    ]
