# Generated by Django 5.1.4 on 2025-02-04 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_organization_trial_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='trial_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 13, 58, 29, 84176, tzinfo=datetime.timezone.utc)),
        ),
    ]
