# Generated by Django 5.1.4 on 2025-02-10 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_organization_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='trial_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 10, 28, 48, 397509, tzinfo=datetime.timezone.utc)),
        ),
    ]
