# Generated by Django 5.1.4 on 2025-02-10 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_organization_trial_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='trial_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 10, 29, 44, 7478, tzinfo=datetime.timezone.utc)),
        ),
    ]
