# Generated by Django 5.1.4 on 2025-01-23 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_organization_trial_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='trial_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 22, 12, 40, 5, 214090, tzinfo=datetime.timezone.utc)),
        ),
    ]
