# Generated by Django 5.1.4 on 2025-02-11 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_organization_trial_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='trial_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 23, 24, 11, 995132, tzinfo=datetime.timezone.utc)),
        ),
    ]
