# Generated by Django 5.1.4 on 2025-02-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='price',
            new_name='price_per_month',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_basic_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscribed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscribed_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
