# Generated by Django 5.1.4 on 2025-01-10 20:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_usersubscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='unique_subscription_plan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
