# Generated by Django 5.1.4 on 2025-02-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_rename_price_subscriptionplan_price_per_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscribing_organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
