# Generated by Django 5.1.4 on 2025-01-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscriptionplan_unique_subscription_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=10),
            preserve_default=False,
        ),
    ]
