# Generated by Django 5.1.4 on 2025-02-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_usersubscription_subscribing_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='subscribed_organization_logos/'),
        ),
    ]
