# Generated by Django 5.1.4 on 2025-01-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_usersubscription_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='total_price',
        ),
    ]
