# Generated by Django 5.1.4 on 2025-02-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_remove_usersubscription_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='organization_logo',
            new_name='user_subscription_logo',
        ),
    ]
