# Generated by Django 5.1.4 on 2025-02-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_rename_organization_logo_usersubscription_user_subscription_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='user_subscription_logo',
        ),
    ]
