# Generated by Django 5.1.4 on 2025-02-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_remove_usersubscription_user_subscription_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscribed_organization_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
