# Generated by Django 5.1.4 on 2025-02-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_usersubscription_subscribed_organization_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='allowed_num_0f_uploaded',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
