# Generated by Django 5.1.4 on 2025-02-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_usersubscription_allowed_num_0f_uploaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='allowed_num_0f_uploaded',
            new_name='allowed_num_0f_cert_upload',
        ),
    ]
