# Generated by Django 5.1.4 on 2025-02-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_rename_allowed_num_0f_uploaded_usersubscription_allowed_num_0f_cert_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
