# Generated by Django 5.1.4 on 2025-01-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_category',
            new_name='category',
        ),
    ]
