# Generated by Django 5.0.2 on 2024-12-19 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('users', '0002_alter_customuser_unique_subscriber_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', to_field='unique_subscriber_id'),
        ),
    ]
