# Generated by Django 5.0.2 on 2024-12-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='issuedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
