# Generated by Django 5.0.2 on 2024-12-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
