# Generated by Django 5.1.4 on 2025-01-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_backgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='examination_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
