# Generated by Django 5.1.4 on 2025-01-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_rename_category_certificate_certificate_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_category',
            new_name='category',
        ),
    ]
