# Generated by Django 5.1.4 on 2025-01-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_rename_certificate_category_certificate_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='category',
            new_name='certificate_category',
        ),
    ]
