# Generated by Django 5.1.4 on 2025-01-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_certificate_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
